# This is a basic workflow to help you get started with Actions

name: Addon Artifact

# Controls when the workflow will run
on:
  push:
    tags:
    - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - uses: actions/upload-artifact@v4
        with:
          name: gdx.zip
          path: addons/gdx/

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "*.zip"
